services:
  xinference-worker:
    image: xprobe/xinference:latest-cpu
    container_name: xinference-worker
    restart: always
    network_mode: host
    environment:
      - XINFERENCE_HOME=${XINFERENCE_HOME}
      - XINFERENCE_MODEL_SRC=${XINFERENCE_MODEL_SRC}
    volumes:
      - ${CACHE_PATH}:/data
    command: >
      xinference-worker -e "${ENDPOINT}" -H "${HOST}" --log-level ${LOG_LEVEL}
    stdin_open: true
    tty: true
