FROM vllm/vllm-openai:v0.6.0

COPY . /opt/inference
WORKDIR /opt/inference

ENV NVM_DIR=/usr/local/nvm
ENV NODE_VERSION=14.21.1

# Install system dependencies and Node.js (libfst-dev should be able to solve the errors of pyini)
RUN apt-get -y update \
  && apt install -y wget curl procps git libgl1 libfst-dev cmake libssl-dev swig \
    && printf "\ndeb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ jammy main restricted universe multiverse" >> /etc/apt/sources.list \
    && apt-get -y update \
    && apt-get install -y --only-upgrade libstdc++6 && apt install -y libc6 libnuma1 \
    && mkdir -p $NVM_DIR \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && apt-get -yq clean

RUN wget https://developer.download.nvidia.com/compute/cuda/12.4.0/local_installers/cuda_12.4.0_550.54.14_linux.run && \
    chmod +x cuda_12.4.0_550.54.14_linux.run && \
    ./cuda_12.4.0_550.54.14_linux.run --silent --toolkit --override && \
    rm -f cuda_12.4.0_550.54.14_linux.run

ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.10/dist-packages/nvidia/cublas/lib
# ENV FLASH_ATTENTION_SKIP_CUDA_BUILD=TRUE

# Install pip dependencies
ARG LLAMA_CPP_USE_CUDA=true
ARG PIP_INDEX=https://pypi.org/simple
RUN pip install --upgrade -i "$PIP_INDEX" pip "setuptools<82" wheel && \
    apt-get -y update && \
    ( wget -O openfst-1.7.2.tar.gz http://www.openslr.org/resources/2/openfst-1.7.2.tar.gz \
      || wget -O openfst-1.7.2.tar.gz https://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.7.2.tar.gz ) && \
    tar zxvf openfst-1.7.2.tar.gz && cd openfst-1.7.2 && \
    ./configure --enable-shared --enable-static && make -j$(nproc) && make install && ldconfig && \
    CPLUS_INCLUDE_PATH=/usr/local/include LIBRARY_PATH=/usr/local/lib LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH \
    pip install -i "$PIP_INDEX" pynini==2.1.6.post1 && \
    apt install -y wget curl procps git libgl1 rsync sqlite libpcre3 libpcre3-dev dmidecode libssl-dev perl make build-essential zlib1g-dev && \
    apt-get -yq clean && \
    # use pre-built whl package for llama-cpp-python, otherwise may core dump when init llama in some envs
    pip install -i "$PIP_INDEX" "diskcache>=5.6.1" "jinja2>=2.11.3" && \
    pip install -i "$PIP_INDEX" --upgrade-strategy only-if-needed -r /opt/inference/xinference/deploy/docker/requirements_12.4/requirements-base.txt && \
    pip install -i "$PIP_INDEX" --upgrade-strategy only-if-needed -r /opt/inference/xinference/deploy/docker/requirements_12.4/requirements-ml.txt && \
    pip install -i "$PIP_INDEX" --upgrade-strategy only-if-needed -r /opt/inference/xinference/deploy/docker/requirements_12.4/requirements-models.txt && \
    pip install -i "$PIP_INDEX" transformers==4.55.2 && \
    pip install -i "$PIP_INDEX" --no-deps sglang==0.4.6.post5 && \
    pip install WeTextProcessing==1.0.4.1 --no-deps && \
    pip install -i "$PIP_INDEX" wetext && \
    pip install importlib_resources && \
    pip install -i "$PIP_INDEX" sgl-kernel==0.1.8 && \
    pip install torch==2.7.1 && \
    pip uninstall flashinfer flashinfer-python -y && \
    pip install flashinfer-python==0.2.9rc2 && \
    pip install https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.3.18/flash_attn-2.7.4+cu124torch2.7-cp310-cp310-linux_x86_64.whl && \
    pip install --no-cache-dir --force-reinstall setuptools==68.2.2 && \
    cd /opt/inference && \
    python3 setup.py build_web && \
    git restore . && \
    pip install -i "$PIP_INDEX" --no-deps "." && \
    pip uninstall xllamacpp -y && \
    pip install https://github.com/xorbitsai/xllamacpp/releases/download/v2026.5.9093-cu124/xllamacpp-2026.5.9093-cp310-abi3-linux_x86_64.whl && \
    # clean packages
    pip cache purge

# Install Miniforge3 and FFmpeg
RUN wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/download/4.12.0-0/Miniforge3-4.12.0-0-Linux-x86_64.sh" && \
    bash Miniforge3.sh -b -p /opt/conda && \
    rm Miniforge3.sh

# When installing the Conda environment, only FFmpeg should be installed to avoid modifying the system Python
RUN /opt/conda/bin/conda create -n ffmpeg-env -c conda-forge 'ffmpeg<7' -y && \
    #Create a soft link to the system path
    ln -s /opt/conda/envs/ffmpeg-env/bin/ffmpeg /usr/local/bin/ffmpeg && \
    ln -s /opt/conda/envs/ffmpeg-env/bin/ffprobe /usr/local/bin/ffprobe && \
    # Clear the Conda cache
    /opt/conda/bin/conda clean --all -y

ENV LD_LIBRARY_PATH=/opt/conda/envs/ffmpeg-env/lib:$LD_LIBRARY_PATH



# Override the default entrypoint of the vllm base image
ENTRYPOINT []
CMD ["/bin/bash"]
